const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.HUB_URL||'http://127.0.0.1:4173/harry-learning-hub/');
await page.getByRole('button',{name:'Football Journalism',exact:true}).click();
await page.getByRole('heading',{name:'Football',exact:true}).waitFor();
assert.equal(await page.locator('.news-story').count(),7);
await page.getByRole('link',{name:/Opinion excerpt Hydration disaster/}).click();
await page.getByRole('heading',{name:'Hydration disaster',exact:true}).waitFor();
assert.match(await page.locator('.news-reading-copy').innerText(),/These hydration breaks need to stop/);
assert.equal(await page.locator('main form, main input, main textarea').count(),0);
await page.getByRole('button',{name:'The Record',exact:true}).click();
assert.equal(await page.locator('.history-card').count(),6);assert.equal(await page.locator('.verified-result').count(),6);await page.getByRole('heading',{name:'England 2–1 Norway',exact:true}).waitFor();await page.getByRole('heading',{name:'England 1–2 Argentina',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Spain 2–0 France',exact:true}).count(),2);assert.equal(await page.getByText('Not recorded',{exact:true}).count(),0);
const norway=page.locator('.history-card').filter({has:page.getByRole('heading',{name:'England v Norway',exact:true})});
assert.equal(await norway.getByText('✓ Correct',{exact:true}).count(),1);
assert.equal(await norway.getByText('× Missed',{exact:true}).count(),1);
await norway.getByText('Add your reflection & extra evidence',{exact:true}).click();
await norway.getByLabel('Additional evidence or match notes').fill('Extra-time winner: Bellingham reacted to the rebound.');
await norway.getByLabel('What would you change next time?').fill('Separate the normal-time result from extra time.');
await norway.getByRole('button',{name:'Save archive review'}).click();
await page.reload();await page.getByRole('button',{name:'The Record',exact:true}).click();
await norway.getByText('Add your reflection & extra evidence',{exact:true}).click();
assert.match(await norway.getByLabel('Additional evidence or match notes').inputValue(),/Extra-time winner/);
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('harry-football-desk-v1')));
assert.equal(saved.predictions.length,0);assert.equal(saved.articles.length,0);
await page.getByRole('button',{name:'Stats lab',exact:true}).click();await page.getByText('0 of 0 reviewed matches',{exact:true}).waitFor();
await page.getByRole('button',{name:'The Record',exact:true}).click();await page.getByRole('button',{name:'Lesson trail',exact:true}).click();
assert.equal(await page.locator('.lesson-timeline li').count(),26);
await page.getByRole('button',{name:'Aaron',exact:true}).click();assert.equal(await page.locator('.lesson-timeline li').count(),15);
const ratings=page.locator('.lesson-timeline li').filter({hasText:'Ratings become statistics'});await ratings.getByRole('button',{name:'Revisit topic'}).click();
await page.getByRole('heading',{name:'The ratings desk'}).waitFor();await page.getByRole('button',{name:'Test my recall'}).click();await page.getByRole('radio',{name:'7',exact:true}).check();await page.getByRole('button',{name:'Check my answer'}).click();await page.getByText('That’s right.',{exact:true}).waitFor();
for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const tab of ['Home','Football Journalism','The Record','Review']){await page.getByRole('button',{name:tab,exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} ${tab}`);await page.screenshot({path:`qa/new-${width}-${tab.replaceAll(' ','-')}.png`,fullPage:true});}}
await page.getByRole('button',{name:'Football Journalism',exact:true}).click();await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'200% text journalism');
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: source archive, provenance, read-only articles, historical reflection persistence, no fabricated statistics, both tutors, lesson-to-review navigation, mobile and 200% text.');
