const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.HUB_URL || 'http://127.0.0.1:4173/harry-learning-hub/');await page.getByRole('button',{name:'Matchday',exact:true}).click();await page.getByRole('heading',{name:'Next on your radar'}).waitFor();
await page.screenshot({path:'qa/desktop-matchday.png',fullPage:true});
await page.getByLabel('Home team',{exact:true}).fill('Test Home');await page.getByLabel('Away team',{exact:true}).fill('Test Away');
await page.getByLabel('Event 1',{exact:true}).fill('Home score first');await page.getByRole('button',{name:'Add an event'}).click();await page.getByLabel('Event 2',{exact:true}).fill('There is a penalty');
await page.getByLabel('What makes you think that?').fill('Home created more chances in the last three matches. Away can still threaten on the break.');
await page.getByRole('button',{name:'Lock prediction'}).click();await page.getByRole('heading',{name:'Test Home v Test Away'}).waitFor();
await page.reload();await page.getByRole('button',{name:'Matchday',exact:true}).click();await page.getByRole('button',{name:/Test Home v Test Away/}).click();
await page.getByLabel('Actual home goals').fill('3');await page.getByLabel('Actual away goals').fill('1');await page.getByLabel('Result source').fill('Practice result for QA');
await page.getByLabel('Result for event 1').selectOption('yes');await page.getByLabel('Result for event 2').selectOption('no');
await page.getByRole('button',{name:'Save result & compare'}).click();await page.getByText('2 / 5 points',{exact:true}).waitFor();
await page.getByLabel('What will you take into the next match?').fill('Chance creation helped. Next time I will check who starts.');await page.getByRole('button',{name:'Save reflection'}).click();
await page.screenshot({path:'qa/desktop-review.png',fullPage:true});
await page.getByRole('button',{name:'Stats lab',exact:true}).click();await page.getByText('100%',{exact:true}).first().waitFor();
await page.getByLabel('What percentage were correct?').fill('60');await page.getByRole('button',{name:'Check answer'}).click();await page.getByText('Correct: 6 ÷ 10 × 100 = 60%.').waitFor();await page.screenshot({path:'qa/desktop-stats.png',fullPage:true});
await page.getByRole('button',{name:'Football Journalism',exact:true}).click();await page.getByRole('link',{name:/Opinion excerpt Hydration disaster/}).click();await page.getByRole('heading',{name:'Hydration disaster',exact:true}).waitFor();assert.equal(await page.locator('main textarea, main input, main form').count(),0);
await page.getByRole('button',{name:'Teacher',exact:true}).click();await page.getByLabel('Teaching note').fill('Next lesson: strengthen the counterargument.');await page.getByRole('button',{name:'Save teaching note'}).click();
const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export backup'}).click()]);await download.saveAs('qa/test-backup.json');const saved=JSON.parse(await fs.readFile('qa/test-backup.json','utf8'));assert.equal(saved.predictions[0].reflection,'Chance creation helped. Next time I will check who starts.');assert.equal(saved.predictions[0].teacherNote,'Next lesson: strengthen the counterargument.');assert.equal(saved.articles.length,0);
await page.getByLabel('Import backup file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":2}')});await page.getByText('This is not a Football Desk backup.').waitFor();
await page.getByLabel('Import backup file').setInputFiles('qa/test-backup.json');await page.getByRole('button',{name:'Replace saved work with backup'}).click();await page.getByText('Backup restored.').waitFor();
await page.reload();await page.getByRole('button',{name:'Teacher',exact:true}).click();assert.equal(await page.getByLabel('Teaching note').inputValue(),'Next lesson: strengthen the counterargument.');
for(const width of [390,768]){await page.setViewportSize({width,height:844});for(const tab of ['Matchday','Football Journalism','Stats lab','Teacher']){await page.getByRole('button',{name:tab,exact:true}).click();await page.screenshot({path:`qa/${width}-${tab.replaceAll(' ','-')}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} ${tab} overflow`)}}
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Matchday',exact:true}).click();await page.getByRole('button',{name:/Test Home v Test Away/}).click();await page.screenshot({path:'qa/mobile-review.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);console.log('PASS: create, lock, reload, results, scoring, reflection, stats, maths, article reading, teacher notes, backup export/import, corrupt backup rejection, desktop/mobile layouts.');await browser.close();
