import { navigate } from './navigation.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.HUB_URL||'http://127.0.0.1:4173/harry-learning-hub/');await page.getByRole('heading',{name:'Make it stick.'}).waitFor();await page.screenshot({path:'qa/hub-home-desktop.png',fullPage:true});
await navigate(page,'Review');await page.getByRole('button',{name:/Maths · 3 QUESTIONS Percentages & discounts/}).click();await page.getByText('1. Out of 100',{exact:true}).click();await page.getByText('40% means 40 out of 100.',{exact:false}).waitFor();await page.getByRole('button',{name:'Test my recall'}).click();
await page.getByRole('radio',{name:'4',exact:true}).check();await page.getByRole('button',{name:'Check my answer'}).click();await page.getByText('Not quite — here’s the idea.').waitFor();await page.getByRole('button',{name:'Next question'}).click();
await page.getByRole('radio',{name:'2',exact:true}).check();await page.getByRole('button',{name:'Check my answer'}).click();await page.getByRole('button',{name:'Next question'}).click();await page.getByRole('radio',{name:'£20',exact:true}).check();await page.getByRole('button',{name:'Check my answer'}).click();await page.getByRole('button',{name:'See topic progress'}).click();await page.getByRole('heading',{name:'2 / 3 correct on your latest checks'}).waitFor();
await page.getByRole('button',{name:'Retry questions to revisit'}).click();await page.getByText('QUESTION 1 / 1',{exact:true}).waitFor();await page.getByRole('radio',{name:'0.4',exact:true}).check();await page.getByRole('button',{name:'Check my answer'}).click();await page.getByRole('button',{name:'See topic progress'}).click();await page.getByRole('heading',{name:'3 / 3 correct on your latest checks'}).waitFor();
await page.reload();await page.getByText('3 / 36 correct on latest checks',{exact:true}).waitFor();await navigate(page,'Review');assert.equal(await page.locator('.topic-card').count(),12);assert.equal(await page.getByRole('button',{name:'English',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:/Build a PEEL paragraph/}).count(),0);await page.screenshot({path:'qa/hub-review-desktop.png',fullPage:true});
for(const width of [390,768]){await page.setViewportSize({width,height:844});for(const tab of ['Home','Review','Matchday','Football Journalism','Stats lab','Teacher']){await navigate(page,tab);await page.screenshot({path:`qa/hub-${width}-${tab.replaceAll(' ','-')}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}}
assert.deepEqual(errors,[]);console.log('PASS: hub home, source-based notes, maths questions, English review removed, wrong/right feedback, retry missed only, persistent latest-check progress, all sections at desktop/tablet/mobile.');await browser.close();
